name: PageSpeed Insights

jobs:
  pagespeed:
    steps:
      - name: Run PageSpeed Insights
        uses: JakePartusch/psi-action@v1.3
        with:
          url: 'https://jolly-part.surge.sh/'
          strategy: 'desktop'
          key: ${{ secrets.PAGESPEED_API_KEY }}
          threshold: 70